// === TWOJE FISZKI I QUIZY ===
const deckDuty = {
  id:'duty',title:'Obowiązki dyżurnego',cards:[
    {question:'Kto może zostać wyznaczony na dyżurnego pododdziału?',answer:'Żołnierz z korpusu podoficerów lub szeregowych (marynarzy).',quote:'329. Na dyżurnego pododdziału wyznacza się żołnierza z korpusu podoficerów lub szeregowych (marynarzy).'},
    {question:'Komu podlega dyżurny pododdziału?',answer:'Dowódcy pododdziału, a pod względem służby – oficerowi dyżurnemu jednostki (instytucji) wojskowej.',quote:'330. Dyżurny pododdziału podlega dowódcy pododdziału, a pod względem służby oficerowi dyżurnemu jednostki (instytucji) wojskowej.'},
    {question:'Czy dyżurny pododdziału ma prawo wydawania rozkazów?',answer:'Tak, ale tylko tych, które wynikają z obowiązków określonych w instrukcji pełnienia służby.',quote:'331. Dyżurny pododdziału ma prawo wydawania rozkazów wynikających z obowiązków określonych w instrukcji pełnienia służby.'},
    {question:'Jaki jest główny zakres działania dyżurnego pododdziału? (6 obowiązków)',answer:'1. Realizacja zadań gotowości do działań, 2. Realizacja zadań zarządzania kryzysowego, 3. Nadzór nad magazynem broni, 4. Wydawanie i przyjmowanie sprzętu z magazynu broni, 5. Nadzór nad porządkiem dnia, 6. Sprawdzanie wyglądu żołnierzy wychodzących poza rejon.',quote:'332. Do zakresu działania dyżurnego pododdziału należy w szczególności: a) realizacja zadań osiągania gotowości do podjęcia działań..., b) realizacja zadań w zakresie zarządzania kryzysowego..., c) nadzór nad pododdziałowym magazynem broni, d) wydawanie i przyjmowanie sprzętu wojskowego..., e) nadzór nad przestrzeganiem porządku dnia..., f) sprawdzenie wyglądu zewnętrznego umundurowanych żołnierzy...'},
    {question:'Co robi dyżurny pododdziału bezpośrednio po odprawie służb?',answer:'Przejmuje dokumentację zgodnie z wykazem i sprawdza zabezpieczenie pododdziałowego magazynu broni.',quote:'333. Po odprawie służb dyżurny pododdziału obejmujący służbę przejmuje dokumentację zgodnie z wykazem dokumentów, sprawdza zabezpieczenie pododdziałowego magazynu broni.'},
    {question:'Komu dyżurny pododdziału melduje fakt objęcia lub zdania służby?',answer:'Dowódcy pododdziału oraz oficerowi dyżurnemu jednostki (instytucji) wojskowej.',quote:'334. Dyżurny pododdziału melduje dowódcy pododdziału i oficerowi dyżurnemu jednostki (instytucji) wojskowej fakt zdania lub objęcia służby.'},
    {question:'Co w sytuacji, gdy objęcie lub zdanie służby następuje po godzinach służbowych?',answer:'Dyżurny pododdziału melduje ten fakt (tylko) oficerowi dyżurnemu jednostki.',quote:'335. Jeżeli zdanie (objęcie) służby następuje po godzinach służbowych, dyżurny pododdziału melduje ten fakt oficerowi dyżurnemu jednostki (instytucji) wojskowej.'},
    {question:'W jakiej sytuacji dyżurny pododdziału składa meldunek pomocnikowi oficera dyżurnego?',answer:'Gdy pomocnik oficera dyżurnego posiada równy lub wyższy stopień wojskowy.',quote:'336. Dyżurny pododdziału składa meldunek pomocnikowi oficera dyżurnego jednostki (instytucji) wojskowej jeżeli pomocnik oficera dyżurnego jednostki (instytucji) wojskowej posiada równy lub wyższy stopień wojskowy.'},
    {question:'Kto podlega dyżurnemu pododdziału?',answer:'Zastępca dyżurnego pododdziału.',quote:'337. Dyżurnemu pododdziału podlega zastępca dyżurnego pododdziału.'},
    {question:'Kto może zostać wyznaczony na zastępcę dyżurnego pododdziału?',answer:'Żołnierz z korpusu podoficerów lub szeregowych (marynarzy) w stopniu wojskowym równym bądź niższym od dyżurnego.',quote:'338. Na zastępcę dyżurnego pododdziału wyznacza się żołnierza z korpusu podoficerów lub szeregowych (marynarzy) w stopniu wojskowym równym bądź niższym od dyżurnego pododdziału'},
    {question:'Komu podlega zastępca dyżurnego pododdziału?',answer:'Dyżurnemu pododdziału.',quote:'339. Zastępca dyżurnego pododdziału podlega dyżurnemu pododdziału.'},
    {question:'Jaki jest zakres działania zastępcy dyżurnego pododdziału?',answer:'a) przyjęcie sprzętu, b) dbanie o czystość, c) wykonywanie rozkazów dyżurnego, d) pełnienie obowiązków dyżurnego w razie jego nieobecności lub niedyspozycji.',quote:'340. Do zakresu działania zastępcy dyżurnego pododdziału w szczególności należy: a. przyjęcie sprzętu..., b. dbanie o czystość..., c. wykonywanie rozkazów dyżurnego..., d. pełnienie obowiązków dyżurnego pododdziału w razie jego nieobecności lub niedyspozycji.'},
    {question:'Dlaczego zastępca dyżurnego musi znać obowiązki dyżurnego?',answer:'Ponieważ w razie nieobecności dyżurnego może mieć konieczność pełnienia wszystkich jego obowiązków wynikających z regulaminu.',quote:'Punkt 340 ppkt d regulaminu można zinterpretować, że zastępca dyżurnego w czasie nieobecności może mieć konieczność pełnić obowiązki, które wynikają z regulaminu, a dotyczą bezpośrednio dyżurnego. Co oznacza, że musi znać jego obowiązki.'}
  ]
};

const deckFirearm = {
  id:'firearm',title:'Konieczność użycia broni palnej',cards:[
    {question:'Jaki jest ogólny warunek użycia broni palnej?',answer:'Musi zaistnieć co najmniej jeden z przypadków wymienionych w ustawie.',quote:'Broni palnej można użyć, gdy zaistnieje co najmniej jeden z następujących przypadków:'},
    {question:'Przypadek 1a: Kiedy można użyć broni do odparcia zamachu na osobę?',answer:'W celu odparcia bezpośredniego, bezprawnego zamachu na życie, zdrowie lub wolność (swoją lub innej osoby).',quote:'1) konieczność odparcia bezpośredniego, bezprawnego zamachu na: a) życie, zdrowie lub wolność uprawnionego lub innej osoby albo konieczność przeciwdziałania czynnościom zmierzającym bezpośrednio do takiego zamachu,'},
    {question:'Przypadek 1b: Użycie broni do ochrony jakich miejsc jest dozwolone?',answer:'Ważnych obiektów, urządzeń lub obszarów.',quote:'b) ważne obiekty, urządzenia lub obszary albo konieczność przeciwdziałania czynnościom zmierzającym bezpośrednio do takiego zamachu,'},
    {question:'Przypadek 1c: Kiedy można użyć broni w obronie mienia?',answer:'Tylko, gdy zamach na mienie stwarza JEDNOCZEŚNIE bezpośrednie zagrożenie dla życia, zdrowia lub wolności.',quote:'c) mienie, który stwarza jednocześnie bezpośrednie zagrożenie życia, zdrowia lub wolności uprawnionego lub innej osoby...'},
    {question:'Przypadek 1d: Użycie broni w celu ochrony granicy państwowej.',answer:'Gdy osoba wymusza przekroczenie granicy przy użyciu pojazdu, broni palnej lub innego niebezpiecznego przedmiotu.',quote:'d) nienaruszalność granicy państwowej przez osobę, która wymusza przekroczenie granicy państwowej przy użyciu pojazdu, broni palnej lub innego niebezpiecznego przedmiotu,'},
    {question:'Przypadek 1e: Kiedy jeszcze można użyć broni w ramach obrony koniecznej?',answer:'Aby zapewnić bezpieczeństwo konwoju lub doprowadzenia.',quote:'e) bezpieczeństwo konwoju lub doprowadzenia;'},
    {question:'Przypadek 2: W jakich dwóch sytuacjach można użyć broni, by przeciwstawić się osobie?',answer:'a) Gdy nie podporządkowuje się wezwaniu do porzucenia broni/niebezpiecznego przedmiotu. b) Gdy usiłuje bezprawnie odebrać broń palną.',quote:'2) konieczność przeciwstawienia się osobie: a) niepodporządkowującej się wezwaniu do natychmiastowego porzucenia broni... b) która usiłuje bezprawnie odebrać broń palną uprawnionemu...'},
    {question:'Przypadek 3: Kiedy użycie broni jest dozwolone w trakcie bezpośredniego pościgu?',answer:'Gdy ścigana jest osoba, wobec której już wcześniej było dozwolone użycie broni, LUB istnieje podejrzenie, że popełniła jedno z przestępstw z katalogu Kodeksu Karnego.',quote:'3) bezpośredni pościg za osobą, wobec której: a) użycie broni palnej było dopuszczalne w przypadkach określonych w pkt 1 lit. a-d i pkt 2, b) istnieje uzasadnione podejrzenie, że popełniła przestępstwo, o którym mowa w art. 115 § 20, art. 148...'},
    {question:'Jakie przestępstwa z Kodeksu Karnego uzasadniają użycie broni (np. w pościgu)?',answer:'M.in. zamach na życie (art. 148), ciężki uszczerbek na zdrowiu (art. 156), sprowadzenie katastrofy (art. 163-165), gwałt (art. 197), wzięcie zakładnika (art. 252), rozbój (art. 280-282).',quote:'art. 115 § 20, art. 148, art. 156 § 1, art. 163-165, art. 197, art. 252 i art. 280-282 ustawy z dnia 6 czerwca 1997 r. – Kodeks karny;'},
    {question:'Przypadek 4a: Kiedy można użyć broni do ujęcia osoby, która schroniła się w trudno dostępnym miejscu?',answer:'Gdy wobec tej osoby już wcześniej dozwolone było użycie broni ORAZ z okoliczności wynika, że może użyć broni lub innego niebezpiecznego przedmiotu.',quote:'4) konieczność: a) ujęcia osoby: (...) - jeżeli schroniła się w miejscu trudno dostępnym, a z okoliczności zdarzenia wynika, że może użyć broni palnej lub innego niebezpiecznego przedmiotu,'},
    {question:'Przypadek 4b: Kiedy można użyć broni, aby udaremnić ucieczkę osoby zatrzymanej/aresztowanej?',answer:'Gdy jej ucieczka stwarza zagrożenie życia/zdrowia, LUB jest podejrzenie, że użyje niebezpiecznych przedmiotów, LUB została zatrzymana za przestępstwo z katalogu K.K.',quote:'b) ujęcia lub udaremnienia ucieczki osoby zatrzymanej (...) jeżeli: - ucieczka tej osoby stwarza zagrożenie życia lub zdrowia (...), - istnieje uzasadnione podejrzenie, że osoba ta może użyć materiałów wybuchowych (...), - pozbawienie wolności nastąpiło w związku z (...) popełnienia przestępstwa, o którym mowa w art. 115 § 20...'},
    {question:'Przypadek 4c: Użycie broni a ucieczka osoby zatrzymanej przez ABW, CBA lub SKW/SWW?',answer:'Można użyć broni do ujęcia lub udaremnienia ucieczki osoby zatrzymanej w związku z podejrzeniem lub stwierdzeniem popełnienia przestępstw podlegających pod te służby.',quote:'c) ujęcia lub udaremnienia ucieczki osoby zatrzymanej (...) w związku z uzasadnionym podejrzeniem lub stwierdzeniem popełnienia (...) przestępstwa, o którym mowa w: art. 5 ust. 1 pkt 2 ustawy (...) o Agencji Bezpieczeństwa Wewnętrznego (...), art. 2 ust. 1 pkt 1 ustawy (...) o Centralnym Biurze Antykorupcyjnym (...), art. 5 ust. 1 pkt 1 ustawy (...) o Służbie Kontrwywiadu Wojskowego...'},
    {question:'Przypadek 5: Kiedy można użyć broni w związku z ucieczką z aresztu lub konwoju?',answer:'W celu udaremnienia ucieczki osoby z aresztu śledczego, zakładu karnego lub osoby konwojowanej, a także w trakcie pościgu za tą osobą.',quote:'5) konieczność udaremnienia ucieczki osoby pozbawionej wolności z aresztu śledczego lub zakładu karnego oraz osoby konwojowanej lub doprowadzanej, a także pościg za tą osobą.'}
  ]
};

// quizy
const quizDy = [
  {q:'Kto, zgodnie z regulaminem, może być wyznaczony na dyżurnego pododdziału?',options:['Tylko podoficer','Żołnierz z korpusu podoficerów lub szeregowych','Każdy żołnierz wyznaczony przez dowódcę'],correct:1},
  {q:'Dyżurny pododdziału melduje objęcie służby po godzinach służbowych:',options:['Dowódcy pododdziału i oficerowi dyżurnemu','Tylko oficerowi dyżurnemu jednostki','Tylko dowódcy pododdziału'],correct:1},
  {q:'Który z poniższych obowiązków NIE NALEŻY do zakresu działania dyżurnego pododdziału?',options:['Nadzór nad pododdziałowym magazynem broni','Udzielanie urlopów żołnierzom','Sprawdzanie wyglądu zewnętrznego umundurowanych żołnierzy'],correct:1},
  {q:'Zastępca dyżurnego podlega:',options:['Dowódcy pododdziału','Oficerowi dyżurnemu','Dyżurnemu pododdziału'],correct:2},
  {q:'W jakiej sytuacji zastępca dyżurnego może pełnić obowiązki dyżurnego?',options:['Tylko na jego wyraźny rozkaz','W razie jego nieobecności lub niedyspozycji','Nigdy, musi zostać wyznaczony nowy dyżurny'],correct:1},
  {q:'Kiedy dyżurny składa meldunek pomocnikowi oficera dyżurnego?',options:['Za każdym razem, gdy go widzi','Tylko, gdy pomocnik ma wyższy stopień wojskowy','Gdy pomocnik ma równy lub wyższy stopień wojskowy'],correct:2}
];

const quizBr = [
  {q:'Użycie broni w celu ochrony mienia jest dopuszczalne, gdy zamach na nie:',options:['Powoduje znaczne straty finansowe','Stwarza jednocześnie bezpośrednie zagrożenie życia, zdrowia lub wolności','Jest dokonywany z użyciem pojazdu'],correct:1},
  {q:'Który przypadek pozwala na użycie broni wobec osoby, która nie reaguje na wezwanie do porzucenia niebezpiecznego przedmiotu?',options:['Odparcie zamachu na ważne obiekty','Przeciwstawienie się osobie (pkt 2a)','Pościg za osobą'],correct:1},
  {q:'Użycie broni jest dozwolone w pościgu za osobą podejrzaną o popełnienie którego z tych przestępstw?',options:['Kradzieży sklepowej','Zniesławienia','Wzięcia zakładnika (art. 252 K.K.)'],correct:2},
  {q:'Co jest warunkiem użycia broni do ujęcia osoby, która schroniła się w trudno dostępnym miejscu?',options:['Musi tam przebywać ponad godzinę','Wcześniejsze użycie broni było wobec niej dopuszczalne ORAZ może ona użyć broni','Jest to teren wojskowy'],correct:1},
  {q:'Użycie broni w celu udaremnienia ucieczki osoby zatrzymanej jest możliwe, gdy:',options:['Osoba biegnie bardzo szybko','Ucieczka stwarza zagrożenie życia lub zdrowia','Osoba jest zatrzymana za wykroczenie drogowe'],correct:1},
  {q:'Na co pozwala punkt 5. regulaminu użycia broni?',options:['Na strzały ostrzegawcze w mieście','Na udaremnienie ucieczki z aresztu, zakładu karnego lub konwoju','Na użycie broni do zatrzymania pojazdu w dowolnej sytuacji'],correct:1},
  {q:'Czy można użyć broni, gdy ktoś próbuje bezprawnie odebrać ją funkcjonariuszowi?',options:['Nie, należy użyć siły fizycznej','Tak, jest to jeden z przypadków (pkt 2b)','Tylko, jeśli napastnik ma broń'],correct:1}
];
